services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ghcr.io/keneojiteli/quiz-app-backend:v1.0.0
    container_name: quiz-app-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
    networks:
      - quiz-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ghcr.io/keneojiteli/quiz-app-frontend:v1.0.0
    container_name: quiz-app-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - quiz-network
    restart: unless-stopped

networks:
  quiz-network:
    driver: bridge