services:
  backend:
    build: # compose should build image from a Dockerfile
      context: ./backend # folder docker can see during build
      dockerfile: Dockerfile # dockerfile to be used
    image: ghcr.io/keneojiteli/quiz-app-backend:local # name of image built with docker compose
    container_name: quiz-app-backend # container name built with docker compose
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
    networks:
      - quiz-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ghcr.io/keneojiteli/quiz-app-frontend:local
    container_name: quiz-app-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - quiz-network
    restart: unless-stopped

networks:
  quiz-network:
    driver: bridge